# Generated by Django 4.1.1 on 2022-10-04 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meallist',
            old_name='meal1',
            new_name='meal_id_1',
        ),
        migrations.RenameField(
            model_name='meallist',
            old_name='meal2',
            new_name='meal_id_2',
        ),
        migrations.RenameField(
            model_name='meallist',
            old_name='meal3',
            new_name='meal_id_3',
        ),
    ]
