# Generated by Django 4.1.1 on 2022-10-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendormeal',
            name='image',
            field=models.ImageField(upload_to='MealImages/%Y/%m/%d/'),
        ),
    ]
